# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:

    runs-on: ubuntu-latest
    container:
      image: docker.io/jsleight1/lgbf:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2.11.0
        with:
          r-version: '4.4.2'
          install-r: false

      - name: Add libPaths
        run: |
          echo -e '.libPaths(c("/usr/local/lib/R/site-library", "/usr/local/lib/R/library"))' > .Rprofile
        shell: bash

      - name: Check package
        run: |
          list.files()
          # devtools::install()
          library(DT)
          library(shinytest2)
          library(shiny)
          utils::sessionInfo()
          # devtools::test()
          devtools::check()
        shell: Rscript {0}

      # - uses: r-lib/actions/check-r-package@v2
      #   with:
      #     upload-snapshots: true
      #     build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
