
on:
  push:
    branches: [6-build-docker-image-using-ci]

name: dockerise.yaml

permissions: read-all

jobs:
  dockerise:
    runs-on: ubuntu-24.04-arm

    steps:
    # - uses: actions/checkout@v4

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ vars.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Get R package version
    #   run: |
    #     version=$(grep Version DESCRIPTION | grep -o "[0-9.]\+")
    #     echo "packageVersion=${version}" >> $GITHUB_ENV
    #   shell: bash {0}

    # - name: Get current date
    #   run: |
    #     echo "DATE=`date +%Y%m%d`" >> $GITHUB_ENV
    #   shell: bash {0}

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
    #   with:
    #     buildkitd-flags: --debug

    - name: dockerise
      run: |
        echo "FROM rocker/r-ver:4.4.2" > Dockerfile

        docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

        more /home/runner/.docker/config.json

        docker buildx \
          build \
          --progress=plain \
          --platform linux/arm64 \
          -t jsleight1/lgbf:test \
          -f Dockerfile \
          --push \
          .

    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     push: true
    #     build-args: |
    #       RVERSION=4.4.2
    #     tags: jsleight1/lgbf:test
    #     # tags: |
    #     #     ${{ secrets.DOCKERHUB_USERNAME }}/lgbf:R${{ env.RVersion }}-{{ env.packageVersion }}-latest
    #     #     ${{ secrets.DOCKERHUB_USERNAME }}/lgbf:R${{ env.RVersion }}-{{ env.packageVersion }}-${{ env.DATE }}

