
on:
  push:
    branches: [6-build-docker-image-using-ci]

name: dockerise.yaml

permissions: read-all

jobs:
  dockerise:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get R package version
      run: |
        ls
        version=$(grep Version DESCRIPTION | grep -o "[0-9.]\+")
        echo "packageVersion=${version}" >> $GITHUB_ENV
      shell: bash {0}

    - name: Print R package version
      run: |
        echo ${{ env.packageVersion }}
      shell: bash {0}
